// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: p2p/protocol/holepunch/pb/holepunch.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HolePunch_Type int32

const (
	HolePunch_CONNECT HolePunch_Type = 100
	HolePunch_SYNC    HolePunch_Type = 300
)

// Enum value maps for HolePunch_Type.
var (
	HolePunch_Type_name = map[int32]string{
		100: "CONNECT",
		300: "SYNC",
	}
	HolePunch_Type_value = map[string]int32{
		"CONNECT": 100,
		"SYNC":    300,
	}
)

func (x HolePunch_Type) Enum() *HolePunch_Type {
	p := new(HolePunch_Type)
	*p = x
	return p
}

func (x HolePunch_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HolePunch_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_protocol_holepunch_pb_holepunch_proto_enumTypes[0].Descriptor()
}

func (HolePunch_Type) Type() protoreflect.EnumType {
	return &file_p2p_protocol_holepunch_pb_holepunch_proto_enumTypes[0]
}

func (x HolePunch_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HolePunch_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HolePunch_Type(num)
	return nil
}

// Deprecated: Use HolePunch_Type.Descriptor instead.
func (HolePunch_Type) EnumDescriptor() ([]byte, []int) {
	return file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescGZIP(), []int{0, 0}
}

// NAT type classification (v2 extension)
type HolePunch_NATType int32

const (
	HolePunch_NAT_UNKNOWN            HolePunch_NATType = 0
	HolePunch_NAT_OPEN               HolePunch_NATType = 1
	HolePunch_NAT_CONE               HolePunch_NATType = 2
	HolePunch_NAT_SYMMETRIC_EASY_INC HolePunch_NATType = 3
	HolePunch_NAT_SYMMETRIC_EASY_DEC HolePunch_NATType = 4
	HolePunch_NAT_SYMMETRIC_HARD     HolePunch_NATType = 5
)

// Enum value maps for HolePunch_NATType.
var (
	HolePunch_NATType_name = map[int32]string{
		0: "NAT_UNKNOWN",
		1: "NAT_OPEN",
		2: "NAT_CONE",
		3: "NAT_SYMMETRIC_EASY_INC",
		4: "NAT_SYMMETRIC_EASY_DEC",
		5: "NAT_SYMMETRIC_HARD",
	}
	HolePunch_NATType_value = map[string]int32{
		"NAT_UNKNOWN":            0,
		"NAT_OPEN":               1,
		"NAT_CONE":               2,
		"NAT_SYMMETRIC_EASY_INC": 3,
		"NAT_SYMMETRIC_EASY_DEC": 4,
		"NAT_SYMMETRIC_HARD":     5,
	}
)

func (x HolePunch_NATType) Enum() *HolePunch_NATType {
	p := new(HolePunch_NATType)
	*p = x
	return p
}

func (x HolePunch_NATType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HolePunch_NATType) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_protocol_holepunch_pb_holepunch_proto_enumTypes[1].Descriptor()
}

func (HolePunch_NATType) Type() protoreflect.EnumType {
	return &file_p2p_protocol_holepunch_pb_holepunch_proto_enumTypes[1]
}

func (x HolePunch_NATType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HolePunch_NATType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HolePunch_NATType(num)
	return nil
}

// Deprecated: Use HolePunch_NATType.Descriptor instead.
func (HolePunch_NATType) EnumDescriptor() ([]byte, []int) {
	return file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescGZIP(), []int{0, 1}
}

// spec: https://github.com/libp2p/specs/blob/master/relay/DCUtR.md
type HolePunch struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     *HolePunch_Type        `protobuf:"varint,1,req,name=type,enum=holepunch.pb.HolePunch_Type" json:"type,omitempty"`
	ObsAddrs [][]byte               `protobuf:"bytes,2,rep,name=ObsAddrs" json:"ObsAddrs,omitempty"`
	// v2 extensions (optional — ignored by v1 peers)
	NatType       *HolePunch_NATType `protobuf:"varint,3,opt,name=natType,enum=holepunch.pb.HolePunch_NATType" json:"natType,omitempty"` // sender's NAT classification
	PunchAddrs    [][]byte           `protobuf:"bytes,4,rep,name=PunchAddrs" json:"PunchAddrs,omitempty"`                                // punch socket's public address (STUN-queried)
	PublicPort    *uint32            `protobuf:"varint,5,opt,name=publicPort" json:"publicPort,omitempty"`                               // latest observed port (for EasySym prediction)
	Tid           *uint32            `protobuf:"varint,6,opt,name=tid" json:"tid,omitempty"`                                             // punch transaction ID (in SYNC message)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolePunch) Reset() {
	*x = HolePunch{}
	mi := &file_p2p_protocol_holepunch_pb_holepunch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolePunch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunch) ProtoMessage() {}

func (x *HolePunch) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_protocol_holepunch_pb_holepunch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunch.ProtoReflect.Descriptor instead.
func (*HolePunch) Descriptor() ([]byte, []int) {
	return file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescGZIP(), []int{0}
}

func (x *HolePunch) GetType() HolePunch_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return HolePunch_CONNECT
}

func (x *HolePunch) GetObsAddrs() [][]byte {
	if x != nil {
		return x.ObsAddrs
	}
	return nil
}

func (x *HolePunch) GetNatType() HolePunch_NATType {
	if x != nil && x.NatType != nil {
		return *x.NatType
	}
	return HolePunch_NAT_UNKNOWN
}

func (x *HolePunch) GetPunchAddrs() [][]byte {
	if x != nil {
		return x.PunchAddrs
	}
	return nil
}

func (x *HolePunch) GetPublicPort() uint32 {
	if x != nil && x.PublicPort != nil {
		return *x.PublicPort
	}
	return 0
}

func (x *HolePunch) GetTid() uint32 {
	if x != nil && x.Tid != nil {
		return *x.Tid
	}
	return 0
}

var File_p2p_protocol_holepunch_pb_holepunch_proto protoreflect.FileDescriptor

const file_p2p_protocol_holepunch_pb_holepunch_proto_rawDesc = "" +
	"\n" +
	")p2p/protocol/holepunch/pb/holepunch.proto\x12\fholepunch.pb\"\x8f\x03\n" +
	"\tHolePunch\x120\n" +
	"\x04type\x18\x01 \x02(\x0e2\x1c.holepunch.pb.HolePunch.TypeR\x04type\x12\x1a\n" +
	"\bObsAddrs\x18\x02 \x03(\fR\bObsAddrs\x129\n" +
	"\anatType\x18\x03 \x01(\x0e2\x1f.holepunch.pb.HolePunch.NATTypeR\anatType\x12\x1e\n" +
	"\n" +
	"PunchAddrs\x18\x04 \x03(\fR\n" +
	"PunchAddrs\x12\x1e\n" +
	"\n" +
	"publicPort\x18\x05 \x01(\rR\n" +
	"publicPort\x12\x10\n" +
	"\x03tid\x18\x06 \x01(\rR\x03tid\"\x1e\n" +
	"\x04Type\x12\v\n" +
	"\aCONNECT\x10d\x12\t\n" +
	"\x04SYNC\x10\xac\x02\"\x86\x01\n" +
	"\aNATType\x12\x0f\n" +
	"\vNAT_UNKNOWN\x10\x00\x12\f\n" +
	"\bNAT_OPEN\x10\x01\x12\f\n" +
	"\bNAT_CONE\x10\x02\x12\x1a\n" +
	"\x16NAT_SYMMETRIC_EASY_INC\x10\x03\x12\x1a\n" +
	"\x16NAT_SYMMETRIC_EASY_DEC\x10\x04\x12\x16\n" +
	"\x12NAT_SYMMETRIC_HARD\x10\x05B7Z5github.com/libp2p/go-libp2p/p2p/protocol/holepunch/pb"

var (
	file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescOnce sync.Once
	file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescData []byte
)

func file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescGZIP() []byte {
	file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescOnce.Do(func() {
		file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_protocol_holepunch_pb_holepunch_proto_rawDesc), len(file_p2p_protocol_holepunch_pb_holepunch_proto_rawDesc)))
	})
	return file_p2p_protocol_holepunch_pb_holepunch_proto_rawDescData
}

var file_p2p_protocol_holepunch_pb_holepunch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_p2p_protocol_holepunch_pb_holepunch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_p2p_protocol_holepunch_pb_holepunch_proto_goTypes = []any{
	(HolePunch_Type)(0),    // 0: holepunch.pb.HolePunch.Type
	(HolePunch_NATType)(0), // 1: holepunch.pb.HolePunch.NATType
	(*HolePunch)(nil),      // 2: holepunch.pb.HolePunch
}
var file_p2p_protocol_holepunch_pb_holepunch_proto_depIdxs = []int32{
	0, // 0: holepunch.pb.HolePunch.type:type_name -> holepunch.pb.HolePunch.Type
	1, // 1: holepunch.pb.HolePunch.natType:type_name -> holepunch.pb.HolePunch.NATType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_p2p_protocol_holepunch_pb_holepunch_proto_init() }
func file_p2p_protocol_holepunch_pb_holepunch_proto_init() {
	if File_p2p_protocol_holepunch_pb_holepunch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_protocol_holepunch_pb_holepunch_proto_rawDesc), len(file_p2p_protocol_holepunch_pb_holepunch_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_protocol_holepunch_pb_holepunch_proto_goTypes,
		DependencyIndexes: file_p2p_protocol_holepunch_pb_holepunch_proto_depIdxs,
		EnumInfos:         file_p2p_protocol_holepunch_pb_holepunch_proto_enumTypes,
		MessageInfos:      file_p2p_protocol_holepunch_pb_holepunch_proto_msgTypes,
	}.Build()
	File_p2p_protocol_holepunch_pb_holepunch_proto = out.File
	file_p2p_protocol_holepunch_pb_holepunch_proto_goTypes = nil
	file_p2p_protocol_holepunch_pb_holepunch_proto_depIdxs = nil
}
